### ISSUE TITLE
Trails data request

### ISSUE THREAD

**Issue by DaveFerBear** [Seattle-Trails-Crew/SeattleTrailsMap#3]
- [x] - HTTP request to get trail data
- [x] - Schemas to parse response properly
- [x] - Cache data (shared preferences?), to avoid loading time on app start
- [x] - Make request in background, then update the UI when the new data is received
- [x] - Properly open and close request -> with such a long, heavy response, the risk of dropped connection, or users closing the app mid-request is heightened.  Handle these edge cases.

**Comment by peacefulhuman** [comment]
- [x] - If no internet connection, open settings.
- [x] - Set up broadcast listener to check connection if previously unavailable and try HTTP request again
